In [1]:
import pandas as pd

In [2]:
#첫번째 공공 데이터 포탈 데이터 가져오기 
data = pd.read_csv('well_processing.csv')
data

,발생일시,관할해경서,발생해역,발생유형,발생원인,기상상태,구조,부상,사망,실종,위도,경도,선 종,톤수,월별,시간대별,발생인원,사고규모
0,2011-12-31 13:20,울산,영해-EEZ,화재,관리소홀,양호,4.0,0.0,0.0,0.0,35,12,어선,9.77,12,13,4.0,0.409417
1,2011-12-31 12:22,통영,항계내,추진기장애,운항부주의,양호,2.0,0.0,0.0,0.0,34,12,어선,4.97,12,12,2.0,0.402414
2,2011-12-31 06:40,여수,영해,전복,운항부주의,양호,5.0,0.0,0.0,0.0,34,12,낚시어선,1.88,12,6,5.0,2.659574
3,2011-12-30 21:15,부산,항계내,화재,정비불량,양호,67.0,0.0,0.0,0.0,35,12,어선,2194.00,12,21,67.0,0.030538
4,2011-12-30 12:00,서귀포,영해-EEZ,기관고장,정비불량,양호,6.0,0.0,0.0,0.0,32,12,어선,8.55,12,12,6.0,0.701754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27786,2021-01-01 15:31,울산,영해,기관손상,정비불량,양호,1.0,0.0,0.0,0.0,35,12,어선,1.93,1,15,1.0,0.518135
27787,2021-01-01 12:02,창원,영해,기관손상,정비불량,양호,15.0,0.0,0.0,0.0,34,12,낚시어선,6.49,1,12,15.0,2.311248
27788,2021-01-01 12:01,통영,협수로,기관손상,정비불량,양호,15.0,0.0,0.0,0.0,34,12,낚시어선,6.49,1,12,15.0,2.311248
27789,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,12.0,0.0,0.0,0.0,34,12,어선,24.00,1,11,12.0,0.500000
27790,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,57.0,0.0,0.0,0.0,34,12,여객선,242.00,1,11,57.0,0.235537

In [3]:
# 두번째 날씨데이터 가져오기
data2 = pd.read_csv('weather_final.csv', encoding='cp949')
data2

,지점,일시,풍속(m/s),풍향(deg),GUST풍속(m/s),현지기압(hPa),습도(%),기온(°C),수온(°C),최대파고(m),유의파고(m),평균파고(m),파주기(sec),파향(deg)
0,울릉도,2011-12-28 0:00,2.1,304.0,4.2,1031.0,45.0,6.2,11.9,3.7,2.2,1.1,6.4,103.0
1,울릉도,2011-12-28 1:00,4.5,293.0,6.9,1030.6,51.0,6.2,11.7,3.6,2.2,1.1,4.3,82.0
2,울릉도,2011-12-28 2:00,4.6,277.0,7.2,1030.4,42.0,6.5,12.4,3.4,2.1,1.0,4.9,206.0
3,울릉도,2011-12-28 3:00,3.2,285.0,6.0,1030.4,40.0,6.5,13.2,3.3,2.1,1.0,4.6,8.0
4,울릉도,2011-12-28 4:00,2.7,276.0,4.6,1030.5,41.0,6.7,13.3,2.6,1.9,1.0,9.1,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984451,홍도,2019-12-31 19:00,8.0,352.0,12.5,1034.9,68.0,2.1,11.5,4.5,2.7,2.0,8.0,347.0
984452,홍도,2019-12-31 20:00,7.3,349.0,11.8,1034.8,59.0,2.1,11.5,3.9,2.5,1.7,7.1,346.0
984453,홍도,2019-12-31 21:00,6.4,345.0,10.0,1034.7,58.0,2.0,11.5,3.9,2.2,1.6,8.0,337.0
984454,홍도,2019-12-31 22:00,7.6,3.0,13.6,1034.0,59.0,2.5,11.5,3.3,2.1,1.5,8.0,351.0
984455,홍도,2019-12-31 23:00,5.5,1.0,10.4,1034.1,58.0,2.3,11.5,3.5,2.0,1.4,7.1,351.0

In [8]:
data['관할해경서'].value_counts()

목포     2669
통영     2555
여수     1959
서귀포    1864
제주     1805
평택     1768
포항     1717
인천     1716
부산     1664
태안     1461
군산     1399
동해     1233
울산     1222
보령     1157
완도     1122
창원     1107
속초      552
부안      407
울진      285
본청      128
          1
Name: 관할해경서, dtype: int64

In [10]:
data['관할해경서'].unique()

array(['울산', '통영', '여수', '부산', '서귀포', '속초', '목포', '인천', '포항', '동해', '평택',
       '태안', '완도', '제주', '군산', '창원', '보령', '부안', '본청', '울진', ' '],
      dtype=object)

In [11]:
data = data[data.관할해경서 != ' '] # 관할해경서 비어있는 1개 삭제
data

,발생일시,관할해경서,발생해역,발생유형,발생원인,기상상태,구조,부상,사망,실종,위도,경도,선 종,톤수,월별,시간대별,발생인원,사고규모
0,2011-12-31 13:20,울산,영해-EEZ,화재,관리소홀,양호,4.0,0.0,0.0,0.0,35,12,어선,9.77,12,13,4.0,0.409417
1,2011-12-31 12:22,통영,항계내,추진기장애,운항부주의,양호,2.0,0.0,0.0,0.0,34,12,어선,4.97,12,12,2.0,0.402414
2,2011-12-31 06:40,여수,영해,전복,운항부주의,양호,5.0,0.0,0.0,0.0,34,12,낚시어선,1.88,12,6,5.0,2.659574
3,2011-12-30 21:15,부산,항계내,화재,정비불량,양호,67.0,0.0,0.0,0.0,35,12,어선,2194.00,12,21,67.0,0.030538
4,2011-12-30 12:00,서귀포,영해-EEZ,기관고장,정비불량,양호,6.0,0.0,0.0,0.0,32,12,어선,8.55,12,12,6.0,0.701754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27786,2021-01-01 15:31,울산,영해,기관손상,정비불량,양호,1.0,0.0,0.0,0.0,35,12,어선,1.93,1,15,1.0,0.518135
27787,2021-01-01 12:02,창원,영해,기관손상,정비불량,양호,15.0,0.0,0.0,0.0,34,12,낚시어선,6.49,1,12,15.0,2.311248
27788,2021-01-01 12:01,통영,협수로,기관손상,정비불량,양호,15.0,0.0,0.0,0.0,34,12,낚시어선,6.49,1,12,15.0,2.311248
27789,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,12.0,0.0,0.0,0.0,34,12,어선,24.00,1,11,12.0,0.500000
27790,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,57.0,0.0,0.0,0.0,34,12,여객선,242.00,1,11,57.0,0.235537

In [12]:
data2['지점'].unique()

array(['울릉도', '덕적도', '칠발도', '거문도', '거제도', '동해 ', '포항', '마라도 ', '외연도',
       '신안', '추자도', '인천', '부안 ', '서귀포', '통영', '울산', '울진', '서해170',
       '서해206', '가거도', '홍도'], dtype=object)

In [13]:
data['관할해경서'].unique()

array(['울산', '통영', '여수', '부산', '서귀포', '속초', '목포', '인천', '포항', '동해', '평택',
       '태안', '완도', '제주', '군산', '창원', '보령', '부안', '본청', '울진'], dtype=object)

In [14]:
data2['지점'].value_counts()

거제도      77625
동해       75530
덕적도      75429
거문도      75415
포항       75348
외연도      74455
마라도      73792
칠발도      73276
울릉도      69436
신안       55681
추자도      46739
울진       35441
통영       34782
서귀포      34630
부안       34139
인천       33942
울산       33901
서해206     1478
서해170     1363
홍도        1038
가거도       1016
Name: 지점, dtype: int64

### 지점과 해경서가 일치 않음을 확인
- 따라서 비슷한 지점과 해경서를 일치 시키고자 함 / 키값으로 사용하기 위함
- 겹쳐지지 않는 지역은 자연스럽게 삭제

In [4]:
data2 = data2.replace('거문도', '여수')
data2['지점'].unique()

array(['울릉도', '덕적도', '칠발도', '여수', '거제도', '동해 ', '포항', '마라도 ', '외연도', '신안',
       '추자도', '인천', '부안 ', '서귀포', '통영', '울산', '울진', '서해170', '서해206',
       '가거도', '홍도'], dtype=object)

In [5]:
data2 = data2.replace('거제도', '부산')
data2['지점'].unique()

array(['울릉도', '덕적도', '칠발도', '여수', '부산', '동해 ', '포항', '마라도 ', '외연도', '신안',
       '추자도', '인천', '부안 ', '서귀포', '통영', '울산', '울진', '서해170', '서해206',
       '가거도', '홍도'], dtype=object)

In [6]:
data2 = data2.replace('울릉도', '속초')
data2['지점'].unique()

array(['속초', '덕적도', '칠발도', '여수', '부산', '동해 ', '포항', '마라도 ', '외연도', '신안',
       '추자도', '인천', '부안 ', '서귀포', '통영', '울산', '울진', '서해170', '서해206',
       '가거도', '홍도'], dtype=object)

In [7]:
data2 = data2.replace('칠발도', '목포')
data2['지점'].unique()

array(['속초', '덕적도', '목포', '여수', '부산', '동해 ', '포항', '마라도 ', '외연도', '신안',
       '추자도', '인천', '부안 ', '서귀포', '통영', '울산', '울진', '서해170', '서해206',
       '가거도', '홍도'], dtype=object)

In [8]:
data2 = data2.replace('추자도', '제주')
data2['지점'].unique()

array(['속초', '덕적도', '목포', '여수', '부산', '동해 ', '포항', '마라도 ', '외연도', '신안',
       '제주', '인천', '부안 ', '서귀포', '통영', '울산', '울진', '서해170', '서해206',
       '가거도', '홍도'], dtype=object)

In [9]:
data2 = data2.replace('외연도', '보령')
data2['지점'].unique()

array(['속초', '덕적도', '목포', '여수', '부산', '동해 ', '포항', '마라도 ', '보령', '신안',
       '제주', '인천', '부안 ', '서귀포', '통영', '울산', '울진', '서해170', '서해206',
       '가거도', '홍도'], dtype=object)

In [10]:
data2 = data2.replace('서해206', '평택')
data2['지점'].unique()

array(['속초', '덕적도', '목포', '여수', '부산', '동해 ', '포항', '마라도 ', '보령', '신안',
       '제주', '인천', '부안 ', '서귀포', '통영', '울산', '울진', '서해170', '평택', '가거도',
       '홍도'], dtype=object)

In [11]:
data2 = data2.replace('서해170', '태안')
data2['지점'].unique()

array(['속초', '덕적도', '목포', '여수', '부산', '동해 ', '포항', '마라도 ', '보령', '신안',
       '제주', '인천', '부안 ', '서귀포', '통영', '울산', '울진', '태안', '평택', '가거도',
       '홍도'], dtype=object)

In [12]:
data2 = data2.replace('신안', '완도')
data2['지점'].unique()

array(['속초', '덕적도', '목포', '여수', '부산', '동해 ', '포항', '마라도 ', '보령', '완도',
       '제주', '인천', '부안 ', '서귀포', '통영', '울산', '울진', '태안', '평택', '가거도',
       '홍도'], dtype=object)

In [13]:
data2 = data2[data2.지점 != '마라도']
data2

,지점,일시,풍속(m/s),풍향(deg),GUST풍속(m/s),현지기압(hPa),습도(%),기온(°C),수온(°C),최대파고(m),유의파고(m),평균파고(m),파주기(sec),파향(deg)
0,속초,2011-12-28 0:00,2.1,304.0,4.2,1031.0,45.0,6.2,11.9,3.7,2.2,1.1,6.4,103.0
1,속초,2011-12-28 1:00,4.5,293.0,6.9,1030.6,51.0,6.2,11.7,3.6,2.2,1.1,4.3,82.0
2,속초,2011-12-28 2:00,4.6,277.0,7.2,1030.4,42.0,6.5,12.4,3.4,2.1,1.0,4.9,206.0
3,속초,2011-12-28 3:00,3.2,285.0,6.0,1030.4,40.0,6.5,13.2,3.3,2.1,1.0,4.6,8.0
4,속초,2011-12-28 4:00,2.7,276.0,4.6,1030.5,41.0,6.7,13.3,2.6,1.9,1.0,9.1,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984451,홍도,2019-12-31 19:00,8.0,352.0,12.5,1034.9,68.0,2.1,11.5,4.5,2.7,2.0,8.0,347.0
984452,홍도,2019-12-31 20:00,7.3,349.0,11.8,1034.8,59.0,2.1,11.5,3.9,2.5,1.7,7.1,346.0
984453,홍도,2019-12-31 21:00,6.4,345.0,10.0,1034.7,58.0,2.0,11.5,3.9,2.2,1.6,8.0,337.0
984454,홍도,2019-12-31 22:00,7.6,3.0,13.6,1034.0,59.0,2.5,11.5,3.3,2.1,1.5,8.0,351.0
984455,홍도,2019-12-31 23:00,5.5,1.0,10.4,1034.1,58.0,2.3,11.5,3.5,2.0,1.4,7.1,351.0

In [14]:
data2 = data2[data2.지점 != '덕적도']
data2

,지점,일시,풍속(m/s),풍향(deg),GUST풍속(m/s),현지기압(hPa),습도(%),기온(°C),수온(°C),최대파고(m),유의파고(m),평균파고(m),파주기(sec),파향(deg)
0,속초,2011-12-28 0:00,2.1,304.0,4.2,1031.0,45.0,6.2,11.9,3.7,2.2,1.1,6.4,103.0
1,속초,2011-12-28 1:00,4.5,293.0,6.9,1030.6,51.0,6.2,11.7,3.6,2.2,1.1,4.3,82.0
2,속초,2011-12-28 2:00,4.6,277.0,7.2,1030.4,42.0,6.5,12.4,3.4,2.1,1.0,4.9,206.0
3,속초,2011-12-28 3:00,3.2,285.0,6.0,1030.4,40.0,6.5,13.2,3.3,2.1,1.0,4.6,8.0
4,속초,2011-12-28 4:00,2.7,276.0,4.6,1030.5,41.0,6.7,13.3,2.6,1.9,1.0,9.1,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984451,홍도,2019-12-31 19:00,8.0,352.0,12.5,1034.9,68.0,2.1,11.5,4.5,2.7,2.0,8.0,347.0
984452,홍도,2019-12-31 20:00,7.3,349.0,11.8,1034.8,59.0,2.1,11.5,3.9,2.5,1.7,7.1,346.0
984453,홍도,2019-12-31 21:00,6.4,345.0,10.0,1034.7,58.0,2.0,11.5,3.9,2.2,1.6,8.0,337.0
984454,홍도,2019-12-31 22:00,7.6,3.0,13.6,1034.0,59.0,2.5,11.5,3.3,2.1,1.5,8.0,351.0
984455,홍도,2019-12-31 23:00,5.5,1.0,10.4,1034.1,58.0,2.3,11.5,3.5,2.0,1.4,7.1,351.0

In [15]:
data2 = data2[data2.지점 != '가거도']
data2

,지점,일시,풍속(m/s),풍향(deg),GUST풍속(m/s),현지기압(hPa),습도(%),기온(°C),수온(°C),최대파고(m),유의파고(m),평균파고(m),파주기(sec),파향(deg)
0,속초,2011-12-28 0:00,2.1,304.0,4.2,1031.0,45.0,6.2,11.9,3.7,2.2,1.1,6.4,103.0
1,속초,2011-12-28 1:00,4.5,293.0,6.9,1030.6,51.0,6.2,11.7,3.6,2.2,1.1,4.3,82.0
2,속초,2011-12-28 2:00,4.6,277.0,7.2,1030.4,42.0,6.5,12.4,3.4,2.1,1.0,4.9,206.0
3,속초,2011-12-28 3:00,3.2,285.0,6.0,1030.4,40.0,6.5,13.2,3.3,2.1,1.0,4.6,8.0
4,속초,2011-12-28 4:00,2.7,276.0,4.6,1030.5,41.0,6.7,13.3,2.6,1.9,1.0,9.1,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984451,홍도,2019-12-31 19:00,8.0,352.0,12.5,1034.9,68.0,2.1,11.5,4.5,2.7,2.0,8.0,347.0
984452,홍도,2019-12-31 20:00,7.3,349.0,11.8,1034.8,59.0,2.1,11.5,3.9,2.5,1.7,7.1,346.0
984453,홍도,2019-12-31 21:00,6.4,345.0,10.0,1034.7,58.0,2.0,11.5,3.9,2.2,1.6,8.0,337.0
984454,홍도,2019-12-31 22:00,7.6,3.0,13.6,1034.0,59.0,2.5,11.5,3.3,2.1,1.5,8.0,351.0
984455,홍도,2019-12-31 23:00,5.5,1.0,10.4,1034.1,58.0,2.3,11.5,3.5,2.0,1.4,7.1,351.0

In [16]:
data2 = data2[data2.지점 != '홍도']
data2

,지점,일시,풍속(m/s),풍향(deg),GUST풍속(m/s),현지기압(hPa),습도(%),기온(°C),수온(°C),최대파고(m),유의파고(m),평균파고(m),파주기(sec),파향(deg)
0,속초,2011-12-28 0:00,2.1,304.0,4.2,1031.0,45.0,6.2,11.9,3.7,2.2,1.1,6.4,103.0
1,속초,2011-12-28 1:00,4.5,293.0,6.9,1030.6,51.0,6.2,11.7,3.6,2.2,1.1,4.3,82.0
2,속초,2011-12-28 2:00,4.6,277.0,7.2,1030.4,42.0,6.5,12.4,3.4,2.1,1.0,4.9,206.0
3,속초,2011-12-28 3:00,3.2,285.0,6.0,1030.4,40.0,6.5,13.2,3.3,2.1,1.0,4.6,8.0
4,속초,2011-12-28 4:00,2.7,276.0,4.6,1030.5,41.0,6.7,13.3,2.6,1.9,1.0,9.1,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982397,평택,2019-12-31 19:00,6.5,68.0,8.9,1036.4,64.0,2.8,12.9,3.5,2.3,1.4,8.7,34.0
982398,평택,2019-12-31 20:00,6.5,140.0,9.4,1036.0,62.0,2.7,12.9,3.2,2.2,1.4,8.9,31.0
982399,평택,2019-12-31 21:00,3.6,111.0,6.6,1035.9,62.0,2.7,13.0,3.2,2.1,1.3,8.1,30.0
982400,평택,2019-12-31 22:00,3.5,143.0,5.5,1035.6,61.0,2.8,13.0,3.0,1.8,1.1,7.6,21.0
982401,평택,2019-12-31 23:00,3.7,78.0,5.8,1035.5,60.0,2.8,12.9,2.3,1.5,1.0,8.1,1.0

In [17]:
data = data[data.관할해경서 != '군산']
data

,발생일시,관할해경서,발생해역,발생유형,발생원인,기상상태,구조,부상,사망,실종,위도,경도,선 종,톤수,월별,시간대별,발생인원,사고규모
0,2011-12-31 13:20,울산,영해-EEZ,화재,관리소홀,양호,4.0,0.0,0.0,0.0,35,12,어선,9.77,12,13,4.0,0.409417
1,2011-12-31 12:22,통영,항계내,추진기장애,운항부주의,양호,2.0,0.0,0.0,0.0,34,12,어선,4.97,12,12,2.0,0.402414
2,2011-12-31 06:40,여수,영해,전복,운항부주의,양호,5.0,0.0,0.0,0.0,34,12,낚시어선,1.88,12,6,5.0,2.659574
3,2011-12-30 21:15,부산,항계내,화재,정비불량,양호,67.0,0.0,0.0,0.0,35,12,어선,2194.00,12,21,67.0,0.030538
4,2011-12-30 12:00,서귀포,영해-EEZ,기관고장,정비불량,양호,6.0,0.0,0.0,0.0,32,12,어선,8.55,12,12,6.0,0.701754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27786,2021-01-01 15:31,울산,영해,기관손상,정비불량,양호,1.0,0.0,0.0,0.0,35,12,어선,1.93,1,15,1.0,0.518135
27787,2021-01-01 12:02,창원,영해,기관손상,정비불량,양호,15.0,0.0,0.0,0.0,34,12,낚시어선,6.49,1,12,15.0,2.311248
27788,2021-01-01 12:01,통영,협수로,기관손상,정비불량,양호,15.0,0.0,0.0,0.0,34,12,낚시어선,6.49,1,12,15.0,2.311248
27789,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,12.0,0.0,0.0,0.0,34,12,어선,24.00,1,11,12.0,0.500000
27790,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,57.0,0.0,0.0,0.0,34,12,여객선,242.00,1,11,57.0,0.235537

In [18]:
data = data[data.관할해경서 != '창원']
data

,발생일시,관할해경서,발생해역,발생유형,발생원인,기상상태,구조,부상,사망,실종,위도,경도,선 종,톤수,월별,시간대별,발생인원,사고규모
0,2011-12-31 13:20,울산,영해-EEZ,화재,관리소홀,양호,4.0,0.0,0.0,0.0,35,12,어선,9.77,12,13,4.0,0.409417
1,2011-12-31 12:22,통영,항계내,추진기장애,운항부주의,양호,2.0,0.0,0.0,0.0,34,12,어선,4.97,12,12,2.0,0.402414
2,2011-12-31 06:40,여수,영해,전복,운항부주의,양호,5.0,0.0,0.0,0.0,34,12,낚시어선,1.88,12,6,5.0,2.659574
3,2011-12-30 21:15,부산,항계내,화재,정비불량,양호,67.0,0.0,0.0,0.0,35,12,어선,2194.00,12,21,67.0,0.030538
4,2011-12-30 12:00,서귀포,영해-EEZ,기관고장,정비불량,양호,6.0,0.0,0.0,0.0,32,12,어선,8.55,12,12,6.0,0.701754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27785,2021-01-01 17:58,울산,항계 내,기관손상,정비불량,양호,7.0,0.0,0.0,0.0,35,12,낚시어선,3.00,1,17,7.0,2.333333
27786,2021-01-01 15:31,울산,영해,기관손상,정비불량,양호,1.0,0.0,0.0,0.0,35,12,어선,1.93,1,15,1.0,0.518135
27788,2021-01-01 12:01,통영,협수로,기관손상,정비불량,양호,15.0,0.0,0.0,0.0,34,12,낚시어선,6.49,1,12,15.0,2.311248
27789,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,12.0,0.0,0.0,0.0,34,12,어선,24.00,1,11,12.0,0.500000
27790,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,57.0,0.0,0.0,0.0,34,12,여객선,242.00,1,11,57.0,0.235537

In [19]:
data = data[data.관할해경서 != '본청']
data

,발생일시,관할해경서,발생해역,발생유형,발생원인,기상상태,구조,부상,사망,실종,위도,경도,선 종,톤수,월별,시간대별,발생인원,사고규모
0,2011-12-31 13:20,울산,영해-EEZ,화재,관리소홀,양호,4.0,0.0,0.0,0.0,35,12,어선,9.77,12,13,4.0,0.409417
1,2011-12-31 12:22,통영,항계내,추진기장애,운항부주의,양호,2.0,0.0,0.0,0.0,34,12,어선,4.97,12,12,2.0,0.402414
2,2011-12-31 06:40,여수,영해,전복,운항부주의,양호,5.0,0.0,0.0,0.0,34,12,낚시어선,1.88,12,6,5.0,2.659574
3,2011-12-30 21:15,부산,항계내,화재,정비불량,양호,67.0,0.0,0.0,0.0,35,12,어선,2194.00,12,21,67.0,0.030538
4,2011-12-30 12:00,서귀포,영해-EEZ,기관고장,정비불량,양호,6.0,0.0,0.0,0.0,32,12,어선,8.55,12,12,6.0,0.701754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27785,2021-01-01 17:58,울산,항계 내,기관손상,정비불량,양호,7.0,0.0,0.0,0.0,35,12,낚시어선,3.00,1,17,7.0,2.333333
27786,2021-01-01 15:31,울산,영해,기관손상,정비불량,양호,1.0,0.0,0.0,0.0,35,12,어선,1.93,1,15,1.0,0.518135
27788,2021-01-01 12:01,통영,협수로,기관손상,정비불량,양호,15.0,0.0,0.0,0.0,34,12,낚시어선,6.49,1,12,15.0,2.311248
27789,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,12.0,0.0,0.0,0.0,34,12,어선,24.00,1,11,12.0,0.500000
27790,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,57.0,0.0,0.0,0.0,34,12,여객선,242.00,1,11,57.0,0.235537

### data1과 data2를 합치기 위한 기준을 발생한 날, 발생한 시간, 지점으로 하고자 하기위해 거치는 작업
- data1에서 발생일시에서 발생한 날 추출
- data1에서 발생한 시간 추출 (분 단위로 되어있음으로) ex) 16:44 -> 16
- data2에서도 발생일시를 추출하여 key라고 할당
- data2에서도 발생한 시간 추출

In [20]:
day = []
for str in data['발생일시']:
    day.append(str[0:10])
len(day)

25157

In [21]:
data['key'] = day

C:\Users\seok\AppData\Local\Temp\ipykernel_14232\2545632516.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['key'] = day

In [22]:
data

,발생일시,관할해경서,발생해역,발생유형,발생원인,기상상태,구조,부상,사망,실종,위도,경도,선 종,톤수,월별,시간대별,발생인원,사고규모,key
0,2011-12-31 13:20,울산,영해-EEZ,화재,관리소홀,양호,4.0,0.0,0.0,0.0,35,12,어선,9.77,12,13,4.0,0.409417,2011-12-31
1,2011-12-31 12:22,통영,항계내,추진기장애,운항부주의,양호,2.0,0.0,0.0,0.0,34,12,어선,4.97,12,12,2.0,0.402414,2011-12-31
2,2011-12-31 06:40,여수,영해,전복,운항부주의,양호,5.0,0.0,0.0,0.0,34,12,낚시어선,1.88,12,6,5.0,2.659574,2011-12-31
3,2011-12-30 21:15,부산,항계내,화재,정비불량,양호,67.0,0.0,0.0,0.0,35,12,어선,2194.00,12,21,67.0,0.030538,2011-12-30
4,2011-12-30 12:00,서귀포,영해-EEZ,기관고장,정비불량,양호,6.0,0.0,0.0,0.0,32,12,어선,8.55,12,12,6.0,0.701754,2011-12-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27785,2021-01-01 17:58,울산,항계 내,기관손상,정비불량,양호,7.0,0.0,0.0,0.0,35,12,낚시어선,3.00,1,17,7.0,2.333333,2021-01-01
27786,2021-01-01 15:31,울산,영해,기관손상,정비불량,양호,1.0,0.0,0.0,0.0,35,12,어선,1.93,1,15,1.0,0.518135,2021-01-01
27788,2021-01-01 12:01,통영,협수로,기관손상,정비불량,양호,15.0,0.0,0.0,0.0,34,12,낚시어선,6.49,1,12,15.0,2.311248,2021-01-01
27789,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,12.0,0.0,0.0,0.0,34,12,어선,24.00,1,11,12.0,0.500000,2021-01-01
27790,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,57.0,0.0,0.0,0.0,34,12,여객선,242.00,1,11,57.0,0.235537,2021-01-01

In [23]:
time = []
for str in data2['일시']:
    if (not(type(str) == float)):
        tap = str[11:13]
        if ':' in tap:
            tap = tap[0]
            time.append(tap)
        else:
            time.append(tap)
len(time)

906973

In [24]:
data2['시간대별'] = time

C:\Users\seok\AppData\Local\Temp\ipykernel_14232\2737476085.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['시간대별'] = time

In [25]:
day = []
for str in data2['일시']:
    day.append(str[0:10])
len(day)

906973

In [26]:
data2['key'] = day

C:\Users\seok\AppData\Local\Temp\ipykernel_14232\2937490678.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['key'] = day

In [27]:
data.rename(columns={'관할해경서':'지점'}, inplace=True)

C:\Users\seok\anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [41]:
data.columns

Index(['발생일시', '지점', '발생해역', '발생유형', '발생원인', '기상상태', '구조', '부상', '사망', '실종',
       '위도', '경도', '선 종', '톤수', '월별', '시간대별', '발생인원', '사고규모', 'key'],
      dtype='object')

mapping을 하기 위해 data type이 같은지 확인  -> 시간대별이 다르므로 int로 타입변경

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25156 entries, 0 to 27790
Data columns (total 19 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   발생일시    25156 non-null  object
 1   지점      25156 non-null  object
 2   발생해역    25156 non-null  object
 3   발생유형    25156 non-null  object
 4   발생원인    25156 non-null  object
 5   기상상태    25156 non-null  object
 6   구조      25127 non-null  float64
 7   부상      25127 non-null  float64
 8   사망      25127 non-null  float64
 9   실종      25127 non-null  float64
 10  위도      25156 non-null  object
 11  경도      25156 non-null  object
 12  선 종     25127 non-null  object
 13  톤수      25127 non-null  float64
 14  월별      25156 non-null  int64
 15  시간대별    25156 non-null  int64
 16  발생인원    25127 non-null  float64
 17  사고규모    24929 non-null  float64
 18  key     25156 non-null  object
dtypes: float64(7), int64(2), object(10)
memory usage: 3.8+ MB

In [44]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 906973 entries, 0 to 982401
Data columns (total 16 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   지점           906973 non-null  object
 1   일시           906973 non-null  object
 2   풍속(m/s)      906973 non-null  float64
 3   풍향(deg)      906973 non-null  float64
 4   GUST풍속(m/s)  906973 non-null  float64
 5   현지기압(hPa)    906973 non-null  float64
 6   습도(%)        906973 non-null  float64
 7   기온(°C)       906973 non-null  float64
 8   수온(°C)       906973 non-null  float64
 9   최대파고(m)      906973 non-null  float64
 10  유의파고(m)      906973 non-null  float64
 11  평균파고(m)      906973 non-null  float64
 12  파주기(sec)     906973 non-null  float64
 13  파향(deg)      906973 non-null  float64
 14  시간대별         906973 non-null  object
 15  key          906973 non-null  object
dtypes: float64(12), object(4)
memory usage: 117.6+ MB

In [28]:
data2 = data2.astype({'시간대별':'int'})
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25157 entries, 0 to 27790
Data columns (total 19 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   발생일시    25157 non-null  object
 1   지점      25157 non-null  object
 2   발생해역    25157 non-null  object
 3   발생유형    25157 non-null  object
 4   발생원인    25157 non-null  object
 5   기상상태    25157 non-null  object
 6   구조      25128 non-null  float64
 7   부상      25128 non-null  float64
 8   사망      25128 non-null  float64
 9   실종      25128 non-null  float64
 10  위도      25157 non-null  object
 11  경도      25157 non-null  object
 12  선 종     25128 non-null  object
 13  톤수      25128 non-null  float64
 14  월별      25157 non-null  int64
 15  시간대별    25157 non-null  int64
 16  발생인원    25128 non-null  float64
 17  사고규모    24930 non-null  float64
 18  key     25157 non-null  object
dtypes: float64(7), int64(2), object(10)
memory usage: 3.8+ MB

## data merging 앞서 제시한 [key, 시간대별, 지점]을 기준으로

In [46]:
final = pd.merge(data, data2, on=['key','시간대별', '지점'])
final

,발생일시,지점,발생해역,발생유형,발생원인,기상상태,구조,부상,사망,실종,...,GUST풍속(m/s),현지기압(hPa),습도(%),기온(°C),수온(°C),최대파고(m),유의파고(m),평균파고(m),파주기(sec),파향(deg)
0,2011-12-31 06:40,여수,영해,전복,운항부주의,양호,5.0,0.0,0.0,0.0,...,7.5,1027.9,51.0,4.8,15.3,1.1,0.7,0.4,6.4,355.0
1,2011-12-30 21:15,부산,항계내,화재,정비불량,양호,67.0,0.0,0.0,0.0,...,4.9,1028.6,58.0,8.6,16.4,2.2,1.4,0.7,6.4,285.0
2,2011-12-30 11:07,속초,영해,침수,정비불량,양호,1.0,0.0,0.0,0.0,...,9.6,1030.0,51.0,5.1,14.4,2.8,2.0,1.0,4.3,359.0
3,2011-12-29 14:15,목포,영해,추진기장애,운항부주의,양호,46.0,0.0,0.0,0.0,...,11.8,1028.4,64.0,4.7,9.0,2.5,1.4,0.7,6.4,214.0
4,2011-12-29 13:35,목포,영해,추진기장애,관리소홀,양호,1.0,0.0,0.0,0.0,...,11.5,1029.4,63.0,4.8,8.9,3.1,1.7,0.8,6.4,222.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11800,2019-01-01 15:53,부산,항계 내,운항저해,연료고갈,양호,4.0,0.0,0.0,0.0,...,7.5,1028.6,50.0,5.4,15.4,1.5,1.0,0.7,9.1,50.0
11801,2019-01-01 14:08,인천,영해,부유물감김,운항부주의,양호,6.0,0.0,0.0,0.0,...,13.0,1032.0,67.0,0.9,6.8,2.6,1.6,1.2,5.3,300.0
11802,2019-01-01 09:14,인천,협수로,침수,운항부주의,양호,2.0,0.0,0.0,0.0,...,10.3,1034.1,66.0,1.2,6.4,1.7,1.0,0.7,4.6,293.0
11803,2019-01-01 07:59,완도,항계 내,좌초/좌주,운항부주의,양호,3.0,0.0,0.0,0.0,...,11.3,1034.1,62.0,3.2,7.6,0.7,0.5,0.3,2.2,184.0
11804,2019-01-01 00:10,서귀포,영해-EEZ,기관손상,정비불량,양호,7.0,0.0,0.0,0.0,...,14.9,1033.4,71.0,6.7,18.9,3.0,1.6,1.2,4.0,342.0

In [48]:
final.to_csv('./final_1.csv',index=False, encoding='utf-8-sig')

### weather데이터 2020이후 데이터 추가로 적용

In [29]:
data3 = pd.read_csv('weather_final2.csv', encoding='cp949')

In [30]:
data3

,지점,일시,풍속(m/s),풍향(deg),GUST풍속(m/s),현지기압(hPa),습도(%),기온(°C),수온(°C),최대파고(m),유의파고(m),평균파고(m),파주기(sec),파향(deg)
0,울릉도,2020-01-01 0:00,6.6,273.0,10.5,1026.4,51.0,3.7,13.7,3.4,2.2,1.6,9.1,42.0
1,울릉도,2020-01-01 2:00,7.5,275.0,10.6,1025.5,53.0,3.8,13.6,3.2,2.0,1.4,9.1,50.0
2,울릉도,2020-01-01 3:00,7.5,284.0,10.6,1025.5,56.0,4.1,13.5,3.4,2.1,1.5,8.0,48.0
3,울릉도,2020-01-01 4:00,4.9,315.0,7.4,1025.2,50.0,3.5,13.5,3.2,1.9,1.3,8.0,40.0
4,울릉도,2020-01-01 5:00,5.8,297.0,8.7,1024.7,54.0,3.6,13.6,2.8,1.8,1.3,8.0,31.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348310,동해78,2021-12-31 19:00,10.9,336.0,15.1,1024.9,50.0,1.7,13.0,3.8,2.4,1.6,8.1,309.0
348311,동해78,2021-12-31 20:00,8.9,334.0,12.2,1025.5,49.0,2.0,13.0,4.1,2.5,1.5,7.8,3.0
348312,동해78,2021-12-31 21:00,8.8,320.0,14.1,1025.7,51.0,2.4,12.9,3.1,2.2,1.3,8.1,74.0
348313,동해78,2021-12-31 22:00,8.2,315.0,10.7,1026.2,50.0,2.7,13.1,3.0,2.0,1.3,7.9,89.0
348314,동해78,2021-12-31 23:00,8.0,307.0,10.8,1026.2,50.0,2.8,13.2,3.8,2.2,1.4,8.2,93.0

In [31]:
data3 = data3.replace('거문도', '여수')
data3 = data3.replace('거제도', '부산')
data3 = data3.replace('울릉도', '속초')
data3 = data3.replace('칠발도', '목포')
data3 = data3.replace('추자도', '제주')
data3 = data3.replace('외연도', '보령')
data3 = data3.replace('서해206', '평택')
data3 = data3.replace('서해170', '태안')
data3 = data3.replace('신안', '완도')
data3['지점'].unique()

array(['속초', '덕적도', '목포', '여수', '부산', '동해 ', '포항', '마라도 ', '보령', '완도',
       '제주', '인천', '부안 ', '서귀포', '통영', '울산', '울진', '태안', '평택', '가거도',
       '홍도', '서해190', '남해239', '남해465', '동해78 '], dtype=object)

In [32]:
data3 = data3[data3.지점 != '마라도']
data3 = data3[data3.지점 != '덕적도']
data3 = data3[data3.지점 != '가거도']
data3 = data3[data3.지점 != '홍도']
data3

,지점,일시,풍속(m/s),풍향(deg),GUST풍속(m/s),현지기압(hPa),습도(%),기온(°C),수온(°C),최대파고(m),유의파고(m),평균파고(m),파주기(sec),파향(deg)
0,속초,2020-01-01 0:00,6.6,273.0,10.5,1026.4,51.0,3.7,13.7,3.4,2.2,1.6,9.1,42.0
1,속초,2020-01-01 2:00,7.5,275.0,10.6,1025.5,53.0,3.8,13.6,3.2,2.0,1.4,9.1,50.0
2,속초,2020-01-01 3:00,7.5,284.0,10.6,1025.5,56.0,4.1,13.5,3.4,2.1,1.5,8.0,48.0
3,속초,2020-01-01 4:00,4.9,315.0,7.4,1025.2,50.0,3.5,13.5,3.2,1.9,1.3,8.0,40.0
4,속초,2020-01-01 5:00,5.8,297.0,8.7,1024.7,54.0,3.6,13.6,2.8,1.8,1.3,8.0,31.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348310,동해78,2021-12-31 19:00,10.9,336.0,15.1,1024.9,50.0,1.7,13.0,3.8,2.4,1.6,8.1,309.0
348311,동해78,2021-12-31 20:00,8.9,334.0,12.2,1025.5,49.0,2.0,13.0,4.1,2.5,1.5,7.8,3.0
348312,동해78,2021-12-31 21:00,8.8,320.0,14.1,1025.7,51.0,2.4,12.9,3.1,2.2,1.3,8.1,74.0
348313,동해78,2021-12-31 22:00,8.2,315.0,10.7,1026.2,50.0,2.7,13.1,3.0,2.0,1.3,7.9,89.0
348314,동해78,2021-12-31 23:00,8.0,307.0,10.8,1026.2,50.0,2.8,13.2,3.8,2.2,1.4,8.2,93.0

In [33]:
time = []
for str in data3['일시']:
    if (not(type(str) == float)):
        tap = str[11:13]
        if ':' in tap:
            tap = tap[0]
            time.append(tap)
        else:
            time.append(tap)
len(time)

304883

In [34]:
data3['시간대별'] = time

In [35]:
day = []
for str in data3['일시']:
    day.append(str[0:10])
len(day)

304883

In [36]:
data3['key'] = day

In [37]:
data3 = data3.astype({'시간대별':'int'})
data3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 304883 entries, 0 to 348314
Data columns (total 16 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   지점           304883 non-null  object
 1   일시           304883 non-null  object
 2   풍속(m/s)      304883 non-null  float64
 3   풍향(deg)      304883 non-null  float64
 4   GUST풍속(m/s)  304883 non-null  float64
 5   현지기압(hPa)    304883 non-null  float64
 6   습도(%)        304883 non-null  float64
 7   기온(°C)       304883 non-null  float64
 8   수온(°C)       304883 non-null  float64
 9   최대파고(m)      304883 non-null  float64
 10  유의파고(m)      304883 non-null  float64
 11  평균파고(m)      304883 non-null  float64
 12  파주기(sec)     304883 non-null  float64
 13  파향(deg)      304883 non-null  float64
 14  시간대별         304883 non-null  int32
 15  key          304883 non-null  object
dtypes: float64(12), int32(1), object(3)
memory usage: 38.4+ MB

### weather data 2011 ~ 2021생성하기위해 concat

In [38]:
df = pd.concat([data2, data3], axis = 0)
df

,지점,일시,풍속(m/s),풍향(deg),GUST풍속(m/s),현지기압(hPa),습도(%),기온(°C),수온(°C),최대파고(m),유의파고(m),평균파고(m),파주기(sec),파향(deg),시간대별,key
0,속초,2011-12-28 0:00,2.1,304.0,4.2,1031.0,45.0,6.2,11.9,3.7,2.2,1.1,6.4,103.0,0,2011-12-28
1,속초,2011-12-28 1:00,4.5,293.0,6.9,1030.6,51.0,6.2,11.7,3.6,2.2,1.1,4.3,82.0,1,2011-12-28
2,속초,2011-12-28 2:00,4.6,277.0,7.2,1030.4,42.0,6.5,12.4,3.4,2.1,1.0,4.9,206.0,2,2011-12-28
3,속초,2011-12-28 3:00,3.2,285.0,6.0,1030.4,40.0,6.5,13.2,3.3,2.1,1.0,4.6,8.0,3,2011-12-28
4,속초,2011-12-28 4:00,2.7,276.0,4.6,1030.5,41.0,6.7,13.3,2.6,1.9,1.0,9.1,37.0,4,2011-12-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348310,동해78,2021-12-31 19:00,10.9,336.0,15.1,1024.9,50.0,1.7,13.0,3.8,2.4,1.6,8.1,309.0,19,2021-12-31
348311,동해78,2021-12-31 20:00,8.9,334.0,12.2,1025.5,49.0,2.0,13.0,4.1,2.5,1.5,7.8,3.0,20,2021-12-31
348312,동해78,2021-12-31 21:00,8.8,320.0,14.1,1025.7,51.0,2.4,12.9,3.1,2.2,1.3,8.1,74.0,21,2021-12-31
348313,동해78,2021-12-31 22:00,8.2,315.0,10.7,1026.2,50.0,2.7,13.1,3.0,2.0,1.3,7.9,89.0,22,2021-12-31
348314,동해78,2021-12-31 23:00,8.0,307.0,10.8,1026.2,50.0,2.8,13.2,3.8,2.2,1.4,8.2,93.0,23,2021-12-31

### 최종적인 데이터 생성

In [39]:
final3 = pd.merge(data, df, on=['key','시간대별', '지점'])
final3

,발생일시,지점,발생해역,발생유형,발생원인,기상상태,구조,부상,사망,실종,...,GUST풍속(m/s),현지기압(hPa),습도(%),기온(°C),수온(°C),최대파고(m),유의파고(m),평균파고(m),파주기(sec),파향(deg)
0,2011-12-31 06:40,여수,영해,전복,운항부주의,양호,5.0,0.0,0.0,0.0,...,7.5,1027.9,51.0,4.8,15.3,1.1,0.7,0.4,6.4,355.0
1,2011-12-30 21:15,부산,항계내,화재,정비불량,양호,67.0,0.0,0.0,0.0,...,4.9,1028.6,58.0,8.6,16.4,2.2,1.4,0.7,6.4,285.0
2,2011-12-30 11:07,속초,영해,침수,정비불량,양호,1.0,0.0,0.0,0.0,...,9.6,1030.0,51.0,5.1,14.4,2.8,2.0,1.0,4.3,359.0
3,2011-12-29 14:15,목포,영해,추진기장애,운항부주의,양호,46.0,0.0,0.0,0.0,...,11.8,1028.4,64.0,4.7,9.0,2.5,1.4,0.7,6.4,214.0
4,2011-12-29 13:35,목포,영해,추진기장애,관리소홀,양호,1.0,0.0,0.0,0.0,...,11.5,1029.4,63.0,4.8,8.9,3.1,1.7,0.8,6.4,222.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17437,2021-01-01 17:58,울산,항계 내,기관손상,정비불량,양호,7.0,0.0,0.0,0.0,...,9.7,1023.9,56.0,5.0,16.0,2.3,1.3,0.9,9.1,58.0
17438,2021-01-01 15:31,울산,영해,기관손상,정비불량,양호,1.0,0.0,0.0,0.0,...,8.9,1023.9,55.0,4.4,16.0,3.0,1.7,1.2,8.0,44.0
17439,2021-01-01 12:01,통영,협수로,기관손상,정비불량,양호,15.0,0.0,0.0,0.0,...,10.3,1027.0,62.0,3.0,11.9,1.3,0.9,0.6,3.4,305.0
17440,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,12.0,0.0,0.0,0.0,...,9.6,1027.9,59.0,4.5,14.5,1.7,0.9,0.7,7.1,112.0
17441,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,57.0,0.0,0.0,0.0,...,9.6,1027.9,59.0,4.5,14.5,1.7,0.9,0.7,7.1,112.0

In [40]:
final3.to_csv('./final_2.csv',index=False, encoding='utf-8-sig')