In [2]:
import pandas as pd

In [3]:
# data_load
data1 = pd.read_csv('ocean_2011.csv', encoding='cp949')
data2 = pd.read_csv('ocean_2012.csv', encoding='cp949')
data3 = pd.read_csv('ocean_2013.csv', encoding='cp949')
data4 = pd.read_csv('ocean_2014.csv', encoding='cp949')
data5 = pd.read_csv('ocean_2015.csv', encoding='cp949')
data6 = pd.read_csv('ocean_2016.csv', encoding='cp949')
data7 = pd.read_csv('ocean_2017.csv', encoding='cp949')
data8 = pd.read_csv('ocean_2018.csv', encoding='cp949')
data9 = pd.read_csv('ocean_2019.csv', encoding='cp949')
data10 = pd.read_csv('ocean_2020.csv', encoding='cp949')
data11 = pd.read_csv('ocean_2021.csv', encoding='cp949')

- data9를 기준으로 같은 값을 가지지만 컬럼명이 다른 것이 존재!
- 최근 데이터를 기준으로 컬럼명 일치 시키기는 작업을 rename으로 시행함
- 선종2, 톤수2, 선종3, 톤수3을 가진 데이터가 적고 또한, 사고선박수와 일치 하지 않으므로 삭제

In [4]:
data1.columns

Index(['발생일시', '관할해경서', '발생해역', '발생유형', '발생원인', '기상특보', '사고선박수', '구조인원',
       '부상인원', '사망인원', '실종인원', '사고위치', '위도', '경도', '선종1', '톤수1', '선종2', '톤수2',
       '선종3', '톤수3'],
      dtype='object')

### 구조인원 -> 구조, 부상인원 -> 부상, 사망인원 -> 사망, 실종인원 -> 실종, 톤수1 -> 톤수, 선종1 -> 선 종, 기상특보 -> 기상상태

In [15]:
data1.rename(columns={'구조인원':'구조','부상인원':'부상','사망인원':'사망','실종인원':'실종','선종1':'선 종','톤수1':'톤수', '기상특보':'기상상태'}, inplace=True)

In [16]:
data1.columns

Index(['발생일시', '관할해경서', '발생해역', '발생유형', '발생원인', '기상상태', '사고선박수', '구조', '부상',
       '사망', '실종', '사고위치', '위도', '경도', '선 종', '톤수', '선종2', '톤수2', '선종3',
       '톤수3'],
      dtype='object')

In [17]:
data1.drop(['선종2', '선종3', '톤수3', '톤수2'], axis = 1, inplace = True)

In [18]:
data1.columns

Index(['발생일시', '관할해경서', '발생해역', '발생유형', '발생원인', '기상상태', '사고선박수', '구조', '부상',
       '사망', '실종', '사고위치', '위도', '경도', '선 종', '톤수'],
      dtype='object')

In [5]:
data2.columns

Index(['발생일시', '관할해경서', '발생해역', '발생유형', '발생원인', '기상특보', '사고선박수', '구조인원',
       '부상인원', '사망인원', '실종인원', '사고위치', '위도', '경도', '선종1', '톤수1', '선종2', '톤수2',
       '선종3', '톤수3'],
      dtype='object')

In [19]:
data2.rename(columns={'구조인원':'구조','부상인원':'부상','사망인원':'사망','실종인원':'실종','선종1':'선 종','톤수1':'톤수', '기상특보':'기상상태'}, inplace=True)

In [20]:
data2.drop(['선종2', '선종3', '톤수3', '톤수2'], axis = 1, inplace = True)

In [21]:
data2.columns

Index(['발생일시', '관할해경서', '발생해역', '발생유형', '발생원인', '기상상태', '사고선박수', '구조', '부상',
       '사망', '실종', '사고위치', '위도', '경도', '선 종', '톤수'],
      dtype='object')

In [6]:
data3.columns

Index(['발생일시', '관할해경서', '발생해역', '발생유형', '발생원인', '기상특보', '사고선박수', '구조인원',
       '부상인원', '사망인원', '실종인원', '사고위치', '위도', '경도', '선종1', '톤수1', '선종2', '톤수2',
       '선종3', '톤수3'],
      dtype='object')

In [26]:
data3.rename(columns={'구조인원':'구조','부상인원':'부상','사망인원':'사망','실종인원':'실종','선종1':'선 종','톤수1':'톤수', '기상특보':'기상상태'}, inplace=True)

In [24]:
data3.drop(['선종2', '선종3', '톤수3', '톤수2'], axis = 1, inplace = True)

In [27]:
data3.columns

Index(['발생일시', '관할해경서', '발생해역', '발생유형', '발생원인', '기상상태', '사고선박수', '구조', '부상',
       '사망', '실종', '사고위치', '위도', '경도', '선 종', '톤수'],
      dtype='object')

In [7]:
data4.columns

Index(['발생일시', '관할해경서', '발생해역', '발생유형', '발생원인', '기상특보', '사고선박수', '구조인원',
       '부상인원', '사망인원', '실종인원', '사고위치', '위도', '경도', '선종1', '톤수1', '선종2', '톤수2',
       '선종3', '톤수3'],
      dtype='object')

In [28]:
data4.rename(columns={'구조인원':'구조','부상인원':'부상','사망인원':'사망','실종인원':'실종','선종1':'선 종','톤수1':'톤수', '기상특보':'기상상태'}, inplace=True)

In [29]:
data4.drop(['선종2', '선종3', '톤수3', '톤수2'], axis = 1, inplace = True)

In [30]:
data4.columns

Index(['발생일시', '관할해경서', '발생해역', '발생유형', '발생원인', '기상상태', '사고선박수', '구조', '부상',
       '사망', '실종', '사고위치', '위도', '경도', '선 종', '톤수'],
      dtype='object')

In [8]:
data5.columns

Index(['발생일시', '관할해경서', '발생해역', '발생유형', '발생원인', '기상특보', '사고선박수', '구조인원',
       '부상인원', '사망인원', '실종인원', '사고위치', '위도', '경도', '선종1', '톤수1', '선종2', '톤수2',
       '선종3', '톤수3'],
      dtype='object')

In [31]:
data5.rename(columns={'구조인원':'구조','부상인원':'부상','사망인원':'사망','실종인원':'실종','선종1':'선 종','톤수1':'톤수', '기상특보':'기상상태'}, inplace=True)

In [32]:
data5.drop(['선종2', '선종3', '톤수3', '톤수2'], axis = 1, inplace = True)

In [33]:
data5.columns

Index(['발생일시', '관할해경서', '발생해역', '발생유형', '발생원인', '기상상태', '사고선박수', '구조', '부상',
       '사망', '실종', '사고위치', '위도', '경도', '선 종', '톤수'],
      dtype='object')

In [9]:
data6.columns

Index(['발생일시', '관할해경서', '발생해역', '발생유형', '발생원인', '기상특보', '사고선박수', '구조인원',
       '부상인원', '사망인원', '실종인원', '사고위치', '위도', '경도', '선종1', '톤수1', '선종2', '톤수2',
       '선종3', '톤수3'],
      dtype='object')

In [34]:
data6.rename(columns={'구조인원':'구조','부상인원':'부상','사망인원':'사망','실종인원':'실종','선종1':'선 종','톤수1':'톤수', '기상특보':'기상상태'}, inplace=True)

In [35]:
data6.drop(['선종2', '선종3', '톤수3', '톤수2'], axis = 1, inplace = True)

In [36]:
data6.columns

Index(['발생일시', '관할해경서', '발생해역', '발생유형', '발생원인', '기상상태', '사고선박수', '구조', '부상',
       '사망', '실종', '사고위치', '위도', '경도', '선 종', '톤수'],
      dtype='object')

In [10]:
data7.columns

Index(['발생일시', '관할해경서', '발생해역', '발생유형', '발생원인', '기상특보', '사고선박수', '구조인원',
       '부상인원', '사망인원', '실종인원', '사고위치', '위도', '경도', '선종1', '톤수1', '선종2', '톤수2',
       '선종3', '톤수3'],
      dtype='object')

In [37]:
data7.rename(columns={'구조인원':'구조','부상인원':'부상','사망인원':'사망','실종인원':'실종','선종1':'선 종','톤수1':'톤수', '기상특보':'기상상태'}, inplace=True)

In [38]:
data7.drop(['선종2', '선종3', '톤수3', '톤수2'], axis = 1, inplace = True)

In [39]:
data7.columns

Index(['발생일시', '관할해경서', '발생해역', '발생유형', '발생원인', '기상상태', '사고선박수', '구조', '부상',
       '사망', '실종', '사고위치', '위도', '경도', '선 종', '톤수'],
      dtype='object')

In [11]:
data8.columns

Index(['발생일시', '관할해경서', '발생해역', '발생유형', '발생원인', '기상특보', '사고선박수', '구조인원',
       '부상인원', '사망인원', '실종인원', '사고위치', '위도', '경도', '선종1', '톤수1', '선종2', '톤수2',
       '선종3', '톤수3'],
      dtype='object')

In [40]:
data8.rename(columns={'구조인원':'구조','부상인원':'부상','사망인원':'사망','실종인원':'실종','선종1':'선 종','톤수1':'톤수', '기상특보':'기상상태'}, inplace=True)

In [41]:
data8.drop(['선종2', '선종3', '톤수3', '톤수2'], axis = 1, inplace = True)

In [42]:
data8.columns

Index(['발생일시', '관할해경서', '발생해역', '발생유형', '발생원인', '기상상태', '사고선박수', '구조', '부상',
       '사망', '실종', '사고위치', '위도', '경도', '선 종', '톤수'],
      dtype='object')

In [12]:
data9.columns

Index(['발생일시', '관할해경서', '발생해역', '위도', '경도', '기상상태', '발생원인', '발생유형', '사고선박수',
       '발생인원', '구조', '부상', '사망', '실종', '선 종', '톤수'],
      dtype='object')

In [13]:
data10.columns

Index(['발생일시', '월별', '시간대별', '관할해경서', '발생해역', '위도', '경도', '기상상태', '발생원인',
       '발생유형', '사고선박수', '발생인원', '구조', '부상', '사망', '실종', '선 종', '톤수'],
      dtype='object')

data11에 무의미한 컬럼 삭제

In [14]:
data11.columns

Index(['발생일시', '월별', '시간대별', '관할해경서', '발생해역', '위도', '경도', '기상상태', '발생원인',
       '발생유형', '사고선박수', '발생인원', '구조', '부상', '사망', '실종', '선 종', '톤수',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29',
       'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33',
       'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37'],
      dtype='object')

In [43]:
data11.dropna(axis=1, inplace=True, how='all')

In [44]:
data11.columns

Index(['발생일시', '월별', '시간대별', '관할해경서', '발생해역', '위도', '경도', '기상상태', '발생원인',
       '발생유형', '사고선박수', '발생인원', '구조', '부상', '사망', '실종', '선 종', '톤수'],
      dtype='object')

- data10, data11에만 월별과 시간대별 칼럼이 존재
- 이를 처리하여 주기 위해 발생일시에서 월과 시간을 추출하여 나머지 data의 컬럼 생성

In [69]:
month = []
count = 0
for str in data9['발생일시']:
    month.append(str[5:7])
    count += 1

In [70]:
data9['월별'] = month

In [71]:
data9

,발생일시,관할해경서,발생해역,위도,경도,기상상태,발생원인,발생유형,사고선박수,발생인원,구조,부상,사망,실종,선 종,톤수,월별
0,2019-12-31 22:04,포항,영해,0 | 0 | 0,0 | 0 | 0,양호,관리소홀,기타,1,0,0,0,0,0,모터보트,1.07,12
1,2019-12-31 15:13,포항,영해,35 | 52 | 3,129 | 45 | 55,양호,운항부주의,충돌,1,12,12,0,0,0,어선,29.00,12
2,2019-12-31 15:13,포항,영해,35 | 52 | 3,129 | 45 | 55,양호,운항부주의,충돌,1,15,15,0,0,0,화물선,1415.00,12
3,2019-12-31 09:33,통영,협수로,34 | 41 | 6,128 | 3 | 59,양호,운항부주의,부유물감김,1,3,3,0,0,0,어선,4.96,12
4,2019-12-31 08:38,군산,항계 내,35 | 59 | 18,126 | 41 | 43,양호,관리소홀,침수,1,0,0,0,0,0,어선,8.55,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3815,2019-01-01 14:08,인천,영해,37 | 21 | 28,126 | 25 | 49,양호,운항부주의,부유물감김,1,6,6,0,0,0,모터보트,19.50,01
3816,2019-01-01 09:14,인천,협수로,37 | 13 | 0,126 | 9 | 0,양호,운항부주의,침수,1,2,2,0,0,0,어선,7.31,01
3817,2019-01-01 07:59,완도,항계 내,34 | 28 | 52,126 | 56 | 41,양호,운항부주의,좌초/좌주,1,3,3,0,0,0,모터보트,1.33,01
3818,2019-01-01 03:31,태안,영해,36 | 46 | 60,126 | 1 | 0,양호,운항부주의,침몰,1,0,0,0,0,0,기타,0.50,01
3819,2019-01-01 00:10,서귀포,영해-EEZ,32 | 49 | 60,127 | 3 | 0,양호,정비불량,기관손상,1,7,7,0,0,0,어선,22.00,01

In [96]:
time = []
for str in data9['발생일시']:
    time.append(str[11:13])
    
len(time)

3820

In [97]:
data9['시간대별'] = time

In [98]:
data9

,발생일시,관할해경서,발생해역,위도,경도,기상상태,발생원인,발생유형,사고선박수,발생인원,구조,부상,사망,실종,선 종,톤수,월별,시간대별
0,2019-12-31 22:04,포항,영해,0 | 0 | 0,0 | 0 | 0,양호,관리소홀,기타,1,0,0,0,0,0,모터보트,1.07,12,22
1,2019-12-31 15:13,포항,영해,35 | 52 | 3,129 | 45 | 55,양호,운항부주의,충돌,1,12,12,0,0,0,어선,29.00,12,15
2,2019-12-31 15:13,포항,영해,35 | 52 | 3,129 | 45 | 55,양호,운항부주의,충돌,1,15,15,0,0,0,화물선,1415.00,12,15
3,2019-12-31 09:33,통영,협수로,34 | 41 | 6,128 | 3 | 59,양호,운항부주의,부유물감김,1,3,3,0,0,0,어선,4.96,12,09
4,2019-12-31 08:38,군산,항계 내,35 | 59 | 18,126 | 41 | 43,양호,관리소홀,침수,1,0,0,0,0,0,어선,8.55,12,08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3815,2019-01-01 14:08,인천,영해,37 | 21 | 28,126 | 25 | 49,양호,운항부주의,부유물감김,1,6,6,0,0,0,모터보트,19.50,01,14
3816,2019-01-01 09:14,인천,협수로,37 | 13 | 0,126 | 9 | 0,양호,운항부주의,침수,1,2,2,0,0,0,어선,7.31,01,09
3817,2019-01-01 07:59,완도,항계 내,34 | 28 | 52,126 | 56 | 41,양호,운항부주의,좌초/좌주,1,3,3,0,0,0,모터보트,1.33,01,07
3818,2019-01-01 03:31,태안,영해,36 | 46 | 60,126 | 1 | 0,양호,운항부주의,침몰,1,0,0,0,0,0,기타,0.50,01,03
3819,2019-01-01 00:10,서귀포,영해-EEZ,32 | 49 | 60,127 | 3 | 0,양호,정비불량,기관손상,1,7,7,0,0,0,어선,22.00,01,00

### 공통된 칼럼을 가지므로 data 합치기

In [99]:
df = pd.concat([data1, data2, data3, data4, data5, data6, data7, data8, data9, data10, data11], ignore_index=True)

In [100]:
df

,발생일시,관할해경서,발생해역,발생유형,발생원인,기상상태,사고선박수,구조,부상,사망,실종,사고위치,위도,경도,선 종,톤수,월별,시간대별,발생인원
0,2011-12-31 13:20,울산,영해-EEZ,화재,관리소홀,양호,1.0,4.0,0.0,0.0,0.0,울기 동남방 26마일 해상,35|19|00,129|51|00,어선,9.77,12,13,NaN
1,2011-12-31 12:22,통영,항계내,추진기장애,운항부주의,양호,1.0,2.0,0.0,0.0,0.0,"34-40N,128-41-45E 해점",34|40|06,128|41|45,어선,4.97,12,12,NaN
2,2011-12-31 06:40,여수,영해,전복,운항부주의,양호,1.0,5.0,0.0,0.0,0.0,여수시 돌산읍 항대 앞,34|38|65,127|42|23,낚시어선,1.88,12,06,NaN
3,2011-12-30 21:15,부산,항계내,화재,정비불량,양호,1.0,67.0,0.0,0.0,0.0,부산 사하구 감천항 3부두 2선석(35-03.78N 129-00.70E),35|03|78,129|00|70,어선,2194.00,12,21,NaN
4,2011-12-30 12:00,서귀포,영해-EEZ,기관고장,정비불량,양호,1.0,6.0,0.0,0.0,0.0,서귀포 남방 43마일,32|31|00,126|36|00,어선,8.55,12,12,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27864,2021-01-01 15:31,울산,영해,기관손상,정비불량,양호,1.0,1.0,0.0,0.0,0.0,NaN,35 | 20 | 54,129 | 21 | 48,어선,1.93,1,15,1.0
27865,2021-01-01 12:02,창원,영해,기관손상,정비불량,양호,1.0,15.0,0.0,0.0,0.0,NaN,34 | 46 | 6,128 | 41 | 22,낚시어선,6.49,1,12,15.0
27866,2021-01-01 12:01,통영,협수로,기관손상,정비불량,양호,1.0,15.0,0.0,0.0,0.0,NaN,34 | 46 | 50,128 | 41 | 21,낚시어선,6.49,1,12,15.0
27867,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,1.0,12.0,0.0,0.0,0.0,NaN,34 | 36 | 27,127 | 39 | 39,어선,24.00,1,11,12.0
27868,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,1.0,57.0,0.0,0.0,0.0,NaN,34 | 36 | 27,127 | 39 | 39,여객선,242.00,1,11,57.0

In [101]:
data9.columns

Index(['발생일시', '관할해경서', '발생해역', '위도', '경도', '기상상태', '발생원인', '발생유형', '사고선박수',
       '발생인원', '구조', '부상', '사망', '실종', '선 종', '톤수', '월별', '시간대별'],
      dtype='object')

In [102]:
data8.columns

Index(['발생일시', '관할해경서', '발생해역', '발생유형', '발생원인', '기상상태', '사고선박수', '구조', '부상',
       '사망', '실종', '사고위치', '위도', '경도', '선 종', '톤수', '월별', '시간대별'],
      dtype='object')

In [103]:
data11.columns

Index(['발생일시', '월별', '시간대별', '관할해경서', '발생해역', '위도', '경도', '기상상태', '발생원인',
       '발생유형', '사고선박수', '발생인원', '구조', '부상', '사망', '실종', '선 종', '톤수'],
      dtype='object')

## 사고위치 칼럼은 최근 데이터에는 존재 하지 않고 이는 관할해경서 및 발생해역으로 대체가능하다고 판단하여 예전데이터에 사고위치 칼럼 삭제

In [105]:
data1.drop(['사고위치'], axis = 1, inplace = True)
data2.drop(['사고위치'], axis = 1, inplace = True)
data3.drop(['사고위치'], axis = 1, inplace = True)
data4.drop(['사고위치'], axis = 1, inplace = True)
data5.drop(['사고위치'], axis = 1, inplace = True)
data6.drop(['사고위치'], axis = 1, inplace = True)
data7.drop(['사고위치'], axis = 1, inplace = True)
data8.drop(['사고위치'], axis = 1, inplace = True)

In [106]:
data1['발생인원'] = data1['구조'] + data1['부상'] + data1['사망'] + data1['실종']
data2['발생인원'] = data2['구조'] + data2['부상'] + data2['사망'] + data2['실종']
data3['발생인원'] = data3['구조'] + data3['부상'] + data3['사망'] + data3['실종']
data4['발생인원'] = data4['구조'] + data4['부상'] + data4['사망'] + data4['실종']
data5['발생인원'] = data5['구조'] + data5['부상'] + data5['사망'] + data5['실종']
data6['발생인원'] = data6['구조'] + data6['부상'] + data6['사망'] + data6['실종']
data7['발생인원'] = data7['구조'] + data7['부상'] + data7['사망'] + data7['실종']
data8['발생인원'] = data8['구조'] + data8['부상'] + data8['사망'] + data8['실종']

In [107]:
df = pd.concat([data1, data2, data3, data4, data5, data6, data7, data8, data9, data10, data11], ignore_index=True)

In [108]:
df

,발생일시,관할해경서,발생해역,발생유형,발생원인,기상상태,사고선박수,구조,부상,사망,실종,위도,경도,선 종,톤수,월별,시간대별,발생인원
0,2011-12-31 13:20,울산,영해-EEZ,화재,관리소홀,양호,1.0,4.0,0.0,0.0,0.0,35|19|00,129|51|00,어선,9.77,12,13,4.0
1,2011-12-31 12:22,통영,항계내,추진기장애,운항부주의,양호,1.0,2.0,0.0,0.0,0.0,34|40|06,128|41|45,어선,4.97,12,12,2.0
2,2011-12-31 06:40,여수,영해,전복,운항부주의,양호,1.0,5.0,0.0,0.0,0.0,34|38|65,127|42|23,낚시어선,1.88,12,06,5.0
3,2011-12-30 21:15,부산,항계내,화재,정비불량,양호,1.0,67.0,0.0,0.0,0.0,35|03|78,129|00|70,어선,2194.00,12,21,67.0
4,2011-12-30 12:00,서귀포,영해-EEZ,기관고장,정비불량,양호,1.0,6.0,0.0,0.0,0.0,32|31|00,126|36|00,어선,8.55,12,12,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27864,2021-01-01 15:31,울산,영해,기관손상,정비불량,양호,1.0,1.0,0.0,0.0,0.0,35 | 20 | 54,129 | 21 | 48,어선,1.93,1,15,1.0
27865,2021-01-01 12:02,창원,영해,기관손상,정비불량,양호,1.0,15.0,0.0,0.0,0.0,34 | 46 | 6,128 | 41 | 22,낚시어선,6.49,1,12,15.0
27866,2021-01-01 12:01,통영,협수로,기관손상,정비불량,양호,1.0,15.0,0.0,0.0,0.0,34 | 46 | 50,128 | 41 | 21,낚시어선,6.49,1,12,15.0
27867,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,1.0,12.0,0.0,0.0,0.0,34 | 36 | 27,127 | 39 | 39,어선,24.00,1,11,12.0
27868,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,1.0,57.0,0.0,0.0,0.0,34 | 36 | 27,127 | 39 | 39,여객선,242.00,1,11,57.0

위도와 경도는 세분화된 분과 초단위까지 사용하지 않을 것이므로 앞에 있는 도만 차용

In [109]:
df['위도'] = df['위도'].apply(lambda x: x[0:2])
df

,발생일시,관할해경서,발생해역,발생유형,발생원인,기상상태,사고선박수,구조,부상,사망,실종,위도,경도,선 종,톤수,월별,시간대별,발생인원
0,2011-12-31 13:20,울산,영해-EEZ,화재,관리소홀,양호,1.0,4.0,0.0,0.0,0.0,35,129|51|00,어선,9.77,12,13,4.0
1,2011-12-31 12:22,통영,항계내,추진기장애,운항부주의,양호,1.0,2.0,0.0,0.0,0.0,34,128|41|45,어선,4.97,12,12,2.0
2,2011-12-31 06:40,여수,영해,전복,운항부주의,양호,1.0,5.0,0.0,0.0,0.0,34,127|42|23,낚시어선,1.88,12,06,5.0
3,2011-12-30 21:15,부산,항계내,화재,정비불량,양호,1.0,67.0,0.0,0.0,0.0,35,129|00|70,어선,2194.00,12,21,67.0
4,2011-12-30 12:00,서귀포,영해-EEZ,기관고장,정비불량,양호,1.0,6.0,0.0,0.0,0.0,32,126|36|00,어선,8.55,12,12,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27864,2021-01-01 15:31,울산,영해,기관손상,정비불량,양호,1.0,1.0,0.0,0.0,0.0,35,129 | 21 | 48,어선,1.93,1,15,1.0
27865,2021-01-01 12:02,창원,영해,기관손상,정비불량,양호,1.0,15.0,0.0,0.0,0.0,34,128 | 41 | 22,낚시어선,6.49,1,12,15.0
27866,2021-01-01 12:01,통영,협수로,기관손상,정비불량,양호,1.0,15.0,0.0,0.0,0.0,34,128 | 41 | 21,낚시어선,6.49,1,12,15.0
27867,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,1.0,12.0,0.0,0.0,0.0,34,127 | 39 | 39,어선,24.00,1,11,12.0
27868,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,1.0,57.0,0.0,0.0,0.0,34,127 | 39 | 39,여객선,242.00,1,11,57.0

In [110]:
df['경도'] = df['경도'].apply(lambda x: x[0:2])
df

,발생일시,관할해경서,발생해역,발생유형,발생원인,기상상태,사고선박수,구조,부상,사망,실종,위도,경도,선 종,톤수,월별,시간대별,발생인원
0,2011-12-31 13:20,울산,영해-EEZ,화재,관리소홀,양호,1.0,4.0,0.0,0.0,0.0,35,12,어선,9.77,12,13,4.0
1,2011-12-31 12:22,통영,항계내,추진기장애,운항부주의,양호,1.0,2.0,0.0,0.0,0.0,34,12,어선,4.97,12,12,2.0
2,2011-12-31 06:40,여수,영해,전복,운항부주의,양호,1.0,5.0,0.0,0.0,0.0,34,12,낚시어선,1.88,12,06,5.0
3,2011-12-30 21:15,부산,항계내,화재,정비불량,양호,1.0,67.0,0.0,0.0,0.0,35,12,어선,2194.00,12,21,67.0
4,2011-12-30 12:00,서귀포,영해-EEZ,기관고장,정비불량,양호,1.0,6.0,0.0,0.0,0.0,32,12,어선,8.55,12,12,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27864,2021-01-01 15:31,울산,영해,기관손상,정비불량,양호,1.0,1.0,0.0,0.0,0.0,35,12,어선,1.93,1,15,1.0
27865,2021-01-01 12:02,창원,영해,기관손상,정비불량,양호,1.0,15.0,0.0,0.0,0.0,34,12,낚시어선,6.49,1,12,15.0
27866,2021-01-01 12:01,통영,협수로,기관손상,정비불량,양호,1.0,15.0,0.0,0.0,0.0,34,12,낚시어선,6.49,1,12,15.0
27867,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,1.0,12.0,0.0,0.0,0.0,34,12,어선,24.00,1,11,12.0
27868,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,1.0,57.0,0.0,0.0,0.0,34,12,여객선,242.00,1,11,57.0

## 발생해역에서 외국해역 및 EEZ-30망일 이내 북한해역은 목적에 부합하지 않다고 판단하여 삭제

In [111]:
df['발생해역'].value_counts()

영해             15201
항계내             4254
항계 내            3776
영해-EEZ          2380
협수로             1726
공해               300
EEZ 30마일 이내      154
외국해역              63
EEZ-30마일 이내       14
북한해역               1
Name: 발생해역, dtype: int64

In [112]:
df = df[df.발생해역 != '외국해역']
df = df[df.발생해역 != 'EEZ-30마일 이내']
df = df[df.발생해역 != '북한해역']

In [113]:
df

,발생일시,관할해경서,발생해역,발생유형,발생원인,기상상태,사고선박수,구조,부상,사망,실종,위도,경도,선 종,톤수,월별,시간대별,발생인원
0,2011-12-31 13:20,울산,영해-EEZ,화재,관리소홀,양호,1.0,4.0,0.0,0.0,0.0,35,12,어선,9.77,12,13,4.0
1,2011-12-31 12:22,통영,항계내,추진기장애,운항부주의,양호,1.0,2.0,0.0,0.0,0.0,34,12,어선,4.97,12,12,2.0
2,2011-12-31 06:40,여수,영해,전복,운항부주의,양호,1.0,5.0,0.0,0.0,0.0,34,12,낚시어선,1.88,12,06,5.0
3,2011-12-30 21:15,부산,항계내,화재,정비불량,양호,1.0,67.0,0.0,0.0,0.0,35,12,어선,2194.00,12,21,67.0
4,2011-12-30 12:00,서귀포,영해-EEZ,기관고장,정비불량,양호,1.0,6.0,0.0,0.0,0.0,32,12,어선,8.55,12,12,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27864,2021-01-01 15:31,울산,영해,기관손상,정비불량,양호,1.0,1.0,0.0,0.0,0.0,35,12,어선,1.93,1,15,1.0
27865,2021-01-01 12:02,창원,영해,기관손상,정비불량,양호,1.0,15.0,0.0,0.0,0.0,34,12,낚시어선,6.49,1,12,15.0
27866,2021-01-01 12:01,통영,협수로,기관손상,정비불량,양호,1.0,15.0,0.0,0.0,0.0,34,12,낚시어선,6.49,1,12,15.0
27867,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,1.0,12.0,0.0,0.0,0.0,34,12,어선,24.00,1,11,12.0
27868,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,1.0,57.0,0.0,0.0,0.0,34,12,여객선,242.00,1,11,57.0

### 사고선박수는 거의 1이고 위에서 언급했듯이 선종2, 선종3는 삭제하였으므로 의미없는 칼럼이라 판단하여 삭제

In [114]:
df.drop(['사고선박수'], axis = 1, inplace = True)
df

,발생일시,관할해경서,발생해역,발생유형,발생원인,기상상태,구조,부상,사망,실종,위도,경도,선 종,톤수,월별,시간대별,발생인원
0,2011-12-31 13:20,울산,영해-EEZ,화재,관리소홀,양호,4.0,0.0,0.0,0.0,35,12,어선,9.77,12,13,4.0
1,2011-12-31 12:22,통영,항계내,추진기장애,운항부주의,양호,2.0,0.0,0.0,0.0,34,12,어선,4.97,12,12,2.0
2,2011-12-31 06:40,여수,영해,전복,운항부주의,양호,5.0,0.0,0.0,0.0,34,12,낚시어선,1.88,12,06,5.0
3,2011-12-30 21:15,부산,항계내,화재,정비불량,양호,67.0,0.0,0.0,0.0,35,12,어선,2194.00,12,21,67.0
4,2011-12-30 12:00,서귀포,영해-EEZ,기관고장,정비불량,양호,6.0,0.0,0.0,0.0,32,12,어선,8.55,12,12,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27864,2021-01-01 15:31,울산,영해,기관손상,정비불량,양호,1.0,0.0,0.0,0.0,35,12,어선,1.93,1,15,1.0
27865,2021-01-01 12:02,창원,영해,기관손상,정비불량,양호,15.0,0.0,0.0,0.0,34,12,낚시어선,6.49,1,12,15.0
27866,2021-01-01 12:01,통영,협수로,기관손상,정비불량,양호,15.0,0.0,0.0,0.0,34,12,낚시어선,6.49,1,12,15.0
27867,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,12.0,0.0,0.0,0.0,34,12,어선,24.00,1,11,12.0
27868,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,57.0,0.0,0.0,0.0,34,12,여객선,242.00,1,11,57.0

## 단순한 feature extraction 사고규모라는 지표를 톤수당 발생이원으로 추론해보고자 함

In [115]:
df['사고규모'] = df['발생인원']/df['톤수']
df

,발생일시,관할해경서,발생해역,발생유형,발생원인,기상상태,구조,부상,사망,실종,위도,경도,선 종,톤수,월별,시간대별,발생인원,사고규모
0,2011-12-31 13:20,울산,영해-EEZ,화재,관리소홀,양호,4.0,0.0,0.0,0.0,35,12,어선,9.77,12,13,4.0,0.409417
1,2011-12-31 12:22,통영,항계내,추진기장애,운항부주의,양호,2.0,0.0,0.0,0.0,34,12,어선,4.97,12,12,2.0,0.402414
2,2011-12-31 06:40,여수,영해,전복,운항부주의,양호,5.0,0.0,0.0,0.0,34,12,낚시어선,1.88,12,06,5.0,2.659574
3,2011-12-30 21:15,부산,항계내,화재,정비불량,양호,67.0,0.0,0.0,0.0,35,12,어선,2194.00,12,21,67.0,0.030538
4,2011-12-30 12:00,서귀포,영해-EEZ,기관고장,정비불량,양호,6.0,0.0,0.0,0.0,32,12,어선,8.55,12,12,6.0,0.701754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27864,2021-01-01 15:31,울산,영해,기관손상,정비불량,양호,1.0,0.0,0.0,0.0,35,12,어선,1.93,1,15,1.0,0.518135
27865,2021-01-01 12:02,창원,영해,기관손상,정비불량,양호,15.0,0.0,0.0,0.0,34,12,낚시어선,6.49,1,12,15.0,2.311248
27866,2021-01-01 12:01,통영,협수로,기관손상,정비불량,양호,15.0,0.0,0.0,0.0,34,12,낚시어선,6.49,1,12,15.0,2.311248
27867,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,12.0,0.0,0.0,0.0,34,12,어선,24.00,1,11,12.0,0.500000
27868,2021-01-01 11:45,여수,영해,충돌,운항부주의,양호,57.0,0.0,0.0,0.0,34,12,여객선,242.00,1,11,57.0,0.235537

In [116]:
df.to_csv('./well_processing.csv',index=False, encoding='utf-8-sig')